services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    user: 1000:1000
    networks:
      - app-network

  nginx:
    restart: on-failure
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./var/logs/:/var/log/nginx/
      - ./public/:/usr/src/app/public/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app-network

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - app-network

  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
    networks:
      - app-network

volumes:
  database_data:

networks:
  app-network:
    external: false
