services:
  php:
    image: thibaultr0/priv-repo-thib:quai-antique-latest
    container_name: php
    restart: on-failure
    volumes:
      - public-volume:/usr/src/app/public
    env_file:
      - .env
    user: www-data
    networks:
      - app-network

  nginx:
    container_name: nginx
    restart: on-failure
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./var/logs/:/var/log/nginx/
      - public-volume:/usr/src/app/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app-network

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network

  mailer:
    image: schickling/mailcatcher
    networks:
      - app-network

volumes:
  database_data:
  public-volume:

networks:
  app-network:
    external: false
